/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.io.File;
import java.io.IOException;
import utilities.RedeemGiftCode;

/**
 *
 * @author Admin
 */
public class RedeemGiftCodeApp extends javax.swing.JFrame {

    /**
     * Creates new form RedeemGiftCode
     */
    public RedeemGiftCodeApp() {
        initComponents();
        //taResult.setText(this.getClass().getClassLoader().getResource().toString());
        //taResult.setText((new File(this.getClass().getProtectionDomain().getCodeSource().getLocation().getPath())).getParent());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTargetUsername = new javax.swing.JLabel();
        lblTargetPwd = new javax.swing.JLabel();
        lblBranch = new javax.swing.JLabel();
        lblEnvironment = new javax.swing.JLabel();
        lblEventID = new javax.swing.JLabel();
        lblRepeatedTimes = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        taResult = new javax.swing.JTextArea();
        txtTargetUsername = new javax.swing.JTextField();
        txtTargetPwd = new javax.swing.JTextField();
        txtBranch = new javax.swing.JTextField();
        txtEnvironment = new javax.swing.JTextField();
        txtEventID = new javax.swing.JTextField();
        txtRepeatedTimes = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTargetUsername.setText("Target Username:");

        lblTargetPwd.setText("Target Password:");

        lblBranch.setText("Branch:");

        lblEnvironment.setText("Environment:");

        lblEventID.setText("Event ID:");

        lblRepeatedTimes.setText("Repeated Times:");

        taResult.setColumns(20);
        taResult.setRows(5);
        jScrollPane1.setViewportView(taResult);

        txtTargetPwd.setText("Password1");

        txtBranch.setText("trunk");

        txtEnvironment.setText("qa1");

        txtEventID.setText("1118");

        txtRepeatedTimes.setText("1000");

        jButton1.setText("Redeem");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblTargetUsername)
                        .addGap(18, 18, 18)
                        .addComponent(txtTargetUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTargetPwd)
                            .addComponent(lblBranch)
                            .addComponent(lblEnvironment)
                            .addComponent(lblEventID)
                            .addComponent(lblRepeatedTimes))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtTargetPwd, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE)
                            .addComponent(txtBranch)
                            .addComponent(txtEnvironment)
                            .addComponent(txtEventID)
                            .addComponent(txtRepeatedTimes))
                        .addGap(39, 39, 39)
                        .addComponent(jButton1)))
                .addContainerGap(265, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTargetUsername)
                    .addComponent(txtTargetUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTargetPwd)
                    .addComponent(txtTargetPwd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblBranch)
                            .addComponent(txtBranch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblEnvironment)
                            .addComponent(txtEnvironment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jButton1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEventID)
                    .addComponent(txtEventID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRepeatedTimes)
                    .addComponent(txtRepeatedTimes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE)
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        redeemGiftCode();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void redeemGiftCode() {

        rg = new RedeemGiftCode();

        rg.setTaResult(taResult);
        rg.setBranch(this.txtBranch.getText());
        rg.setEnv(this.txtEnvironment.getText());
        rg.setEventID(this.txtEventID.getText());
        rg.setRepeatedTime(Integer.parseInt(this.txtRepeatedTimes.getText()));
        rg.setTargetPwd(this.txtTargetPwd.getText());
        rg.setTargetUser(this.txtTargetUsername.getText());

        rg.start();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RedeemGiftCodeApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RedeemGiftCodeApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RedeemGiftCodeApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RedeemGiftCodeApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RedeemGiftCodeApp().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblBranch;
    private javax.swing.JLabel lblEnvironment;
    private javax.swing.JLabel lblEventID;
    private javax.swing.JLabel lblRepeatedTimes;
    private javax.swing.JLabel lblTargetPwd;
    private javax.swing.JLabel lblTargetUsername;
    private javax.swing.JTextArea taResult;
    private javax.swing.JTextField txtBranch;
    private javax.swing.JTextField txtEnvironment;
    private javax.swing.JTextField txtEventID;
    private javax.swing.JTextField txtRepeatedTimes;
    private javax.swing.JTextField txtTargetPwd;
    private javax.swing.JTextField txtTargetUsername;
    // End of variables declaration//GEN-END:variables
    private RedeemGiftCode rg;
}
